### ISSUE TITLE
Please force HTTPS

### ISSUE THREAD

**Issue by ghost** [asciimoo/go-colly.org#17]
Please force all request to `https`

**Comment by stefins** [comment]
> Please force all request to `https`

I second this

**Comment by luantak** [comment]
This makes colly look really bad. HTTPS isn't even enabled.

**Comment by ghost** [comment]
I used to think colly was the shit, but now i started to build my own crawlers and scrapers and this project looks like shit.

**Comment by asciimoo** [comment]
Thanks for the kind and constructive words. :) Just to be clear: go-colly.org is a fully static HTML site which only contains public data. Indeed, HTTPS is kind of defacto standard nowadays, but in this exact case I don't really see the added value of using HTTPS. I'm not saying that it wouldn't be good to make it available over HTTPS, it's just a lower priority issue for me. Why do you think that it has a high importance?

**Comment by ghost** [comment]
If a user is using https everywhere than the whole site will break and need to disable it completely just to see the page.

Also i am 99% sure it will take less than 15 mins to fix this issue, and only one of the project team members can fix it.

Don't get me wrong, i am not saying the project is bad but for this many developers it could be alot better.
