### ISSUE TITLE
Update the documentation to use the new functional options to NewCollector

### ISSUE THREAD

**Issue by peterhellberg** [asciimoo/go-colly.org#2]
Now that https://github.com/gocolly/colly/pull/82 has been merged we should probably update the documentation to match.

@asciimoo I'm happy to do it if you don't want to :)

## Pages that should be updated: (Might not be a complete list)

 - [x] http://go-colly.org/docs/best_practices/debugging/
 - [x] http://go-colly.org/docs/best_practices/multi_collector/
 - [x] http://go-colly.org/docs/best_practices/crawling/
 - [x] http://go-colly.org/docs/examples/basic/
 - [x] http://go-colly.org/docs/examples/max_depth/
 - [x] http://go-colly.org/docs/examples/multipart/
 - [x] http://go-colly.org/docs/examples/parallel/
 - [x] http://go-colly.org/docs/examples/proxy_switcher/
 - [x] http://go-colly.org/docs/examples/rate_limit/
 - [x] http://go-colly.org/docs/examples/url_filter/
 - [x] http://go-colly.org/docs/examples/coursera_courses/
 - [x] http://go-colly.org/docs/examples/instagram/
 - [x] http://go-colly.org/docs/examples/openedx_courses/
 - [x] http://go-colly.org/docs/examples/xkcd_store/

**Comment by asciimoo** [comment]
Good point, thanks! We also have to update the examples in the colly repo.

**Comment by peterhellberg** [comment]
### http://go-colly.org/docs/best_practices/debugging/

```go
c := colly.NewCollector()
c.SetDebugger(&debug.LogDebugger{})
```
This can be replaced by `c := colly.NewCollector(colly.Debugger(&debug.LogDebugger{}))`

### http://go-colly.org/docs/best_practices/crawling/

```go
c := c.NewCollector()

// Reduce maximum response body size to 1M
c.MaxBodySize := 1024 * 1024

// Don't track visited urls automatically
c.AllowURLRevisit = true
```

This can be replaced by `c := c.NewCollector(colly.MaxBodySize(1024 * 1024), colly.AllowURLRevisit())`

**Comment by peterhellberg** [comment]
Maybe we should add option functions for `WithTransport`, `DisableCookies`, `CookieJar`, `RequestTimeout`, `Proxy`, `ProxyFunc`?

**Comment by asciimoo** [comment]
> Maybe we should add option functions for WithTransport, DisableCookies, CookieJar, RequestTimeout, Proxy, ProxyFunc?

I don't think that it improves the API that much, but duplicates functionality, so I'd vote on don't add. What do you think?

**Comment by asciimoo** [comment]
Docs are updated: 8635de8b234c1c5cf242cc2f29a7d70498d4225e 700095677ee8b8d9eed27f419a1ab951fc82e656 1a9052fd28e57202f5be3e480c9ab75a6ca792a1
